package com.gph.model;

import java.util.Date;

public class DyComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_comment.cid
     *
     * @mbggenerated
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_comment.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_comment.public_id
     *
     * @mbggenerated
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_comment.dy_id
     *
     * @mbggenerated
     */
    private Integer dyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dy_comment.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    private User publisher;


    public User getPublisher() {
        return publisher;
    }

    public void setPublisher(User publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_comment.cid
     *
     * @return the value of dy_comment.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_comment.cid
     *
     * @param cid the value for dy_comment.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_comment.comment
     *
     * @return the value of dy_comment.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_comment.comment
     *
     * @param comment the value for dy_comment.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_comment.public_id
     *
     * @return the value of dy_comment.public_id
     *
     * @mbggenerated
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_comment.public_id
     *
     * @param publicId the value for dy_comment.public_id
     *
     * @mbggenerated
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_comment.dy_id
     *
     * @return the value of dy_comment.dy_id
     *
     * @mbggenerated
     */
    public Integer getDyId() {
        return dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_comment.dy_id
     *
     * @param dyId the value for dy_comment.dy_id
     *
     * @mbggenerated
     */
    public void setDyId(Integer dyId) {
        this.dyId = dyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dy_comment.createtime
     *
     * @return the value of dy_comment.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dy_comment.createtime
     *
     * @param createtime the value for dy_comment.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}